name: dayme_test
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
   sdk: ^3.6.0

dependencies:
   flutter:
      sdk: flutter

   cupertino_icons: ^1.0.8
   flutter_bloc: ^9.0.0
   bloc: ^9.0.0
   isar:
      version: 3.1.8
      hosted: https://pub.isar-community.dev/
   isar_flutter_libs:
      version: 3.1.8
      hosted: https://pub.isar-community.dev/
   meta: ^1.15.0
   get_it: ^8.0.3
   path_provider: ^2.1.5
   equatable: ^2.0.7
   http: ^1.3.0
   flutter_svg: ^2.0.17
   gap: ^3.0.1

dev_dependencies:
   flutter_test:
      sdk: flutter
   build_runner: ^2.4.10
   isar_generator:
      version: 3.1.8
      hosted: https://pub.isar-community.dev/

   flutter_lints: ^5.0.0

flutter:
   uses-material-design: true

   assets:
      - assets/icons/
      - assets/fonts/
   fonts:
      - family: Mariupol
        fonts:
           - asset: assets/fonts/Mariupol-Regular.otf
           - asset: assets/fonts/Mariupol-Bold.otf
           - asset: assets/fonts/Mariupol-Medium.otf
